name: CD (Build and deploy to GAS)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      CLIENTID: ${{ secrets.CLIENTID }}
      CLIENTSECRET: ${{ secrets.CLIENTSECRET }}
      ID_TOKEN: ${{ secrets.ID_TOKEN }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      SCRIPTID: ${{ secrets.SCRIPTID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Insstall Clasp
        run: |
          npm init -y
          npm i clasp -g
      - name: Create .clasprc.json
        run: |
          echo $(cat <<-EOS
          {
            "token": {
              "access_token": "${ACCESS_TOKEN}",
              "scope": "https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/drive.file openid https://www.googleapis.com/auth/service.management https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/logging.read https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/script.webapp.deploy",
              "token_type": "Bearer",
              "id_token": "${ID_TOKEN}",
              "expiry_date": 1697293156057,
              "refresh_token": "${REFRESH_TOKEN}"
            },
            "oauth2ClientSettings": {
              "clientId": "${CLIENTID}",
              "clientSecret": "${CLIENTSECRET}",
              "redirectUri": "http://localhost"
            },
            "isLocalCreds": false
          }
          EOS
          ) > ~/.clasprc.json
      - name: Create .clasp.json
        run: |
          echo $(cat <<-EOS
          {
            "scriptId": "${SCRIPTID}",
            "rootDir": "./src"
          }
          EOS
          ) > ./.clasp.json
      - name: Deploy
        run: |
          clasp push